Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -32,18 +32,16 @@ jobs:
           export KUBECONFIG=./kubeconfig
 
       - name: Deploy to Kubernetes
-        env:
-          KUBECONFIG: ${{ secrets.KUBECONFIG }}
         run: |
           kubectl apply -f deployment.yaml
           kubectl rollout status deployment/my-node-app
 
-      - name: Check deployment status
-        env:
-          KUBECONFIG: ${{ secrets.KUBECONFIG }}
-        run: |
-          if ! kubectl rollout status deployment/my-node-app; then
-            echo "Deployment failed, rolling back..."
-            kubectl rollout undo deployment/my-node-app
-          fi
+      #- name: Check deployment status
+       # env:
+        #  KUBECONFIG: ${{ secrets.KUBECONFIG }}
+        #run: |
+         # if ! kubectl rollout status deployment/my-node-app; then
+         #   echo "Deployment failed, rolling back..."
+          #  kubectl rollout undo deployment/my-node-app
+          #fi
           
